name: Regression End-to-End Tests
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci  # Ensures a clean install

      - name: Verify Cypress Installation
        run: npx cypress verify  # Checks if Cypress is correctly installed

      - name: Run Cypress Tests
        run: npx cypress run
